### PR TITLE
Require node 14.16

### LINKED ISSUE #8: Require Node version 14.16+
Asyncerator assumes some new behavior for stream.pipeline that was introduced in 14.15.5, so set engine >= 14.16.

### PR DESCRIPTION
**Pull request by carlansley**
Fixes #8

### CODE REVIEW

**Comment by ramaghanta** [comment]
just so we don't forget, squerging this PR requires the auto-publish container to be updated to node 14.16.x

**Review by gatsbyz — APPROVED** [review]

**Comment by adcreare** [comment]
autopublish uses 14.15.4 at the moment.  I wont approve this PR until we get AP updated. I'll try and do it tomorrow if mngs isn't too busy

**Review by ramaghanta — APPROVED** [review]
lgtm

**Review by adcreare — APPROVED** [review]
LGTM

**Pull request merged**
